package:
  name: sk_sugar
  version: 0.0.6
source:
  sha256: 7d7d209f7462858a534f2098896737b4fe9519ead3e66d25a6f0730c1b58bdc1
  url: https://files.pythonhosted.org/packages/56/a1/b818bb880942831908302a938ab0d9a5392ed4922774d72ebdfe92be68b3/sk_sugar-0.0.6.tar.gz
about:
  dev_url: https://KrishnaswamyLab.github.io
  doc_url: https://KrishnaswamyLab.github.io
  home: https://KrishnaswamyLab.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python version of SUGAR
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dsm-72
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - sk_sugar
