package:
  name: sk_sugar
  version: 0.0.1
source:
  sha256: e2a3b3a102aeb42c5fb9d2d2480a2bd240a59d574ec09400cdfd4dcb46c78880
  url: https://files.pythonhosted.org/packages/0b/5d/9568a8ad0ea5568e6fa6773f5b55fdc6f276a903aae71ff068ccf186a5d6/sk_sugar-0.0.1.tar.gz
about:
  dev_url: https://dsm-72.github.io
  doc_url: https://dsm-72.github.io
  home: https://dsm-72.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python version of SUGAR
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dsm-72
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - sk_sugar
