package:
  name: sk_sugar
  version: 0.0.5
source:
  sha256: d8d0d2697bf8c2d79f4a7e79a5198fb4fa2caf8dc7278f5823562cc96d87d49c
  url: https://files.pythonhosted.org/packages/4a/9d/640b10539cdb9964727b742364ec29717ee0d13870e7cd84d87b94df8d3f/sk_sugar-0.0.5.tar.gz
about:
  dev_url: https://KrishnaswamyLab.github.io
  doc_url: https://KrishnaswamyLab.github.io
  home: https://KrishnaswamyLab.github.io
  license: Apache Software
  license_family: APACHE
  summary: Python version of SUGAR
build:
  noarch: python
  number: '0'
  script: '{{ PYTHON }} -m pip install . -vv'
extra:
  recipe-maintainers:
  - dsm-72
requirements:
  host:
  - pip
  - python
  - packaging
  run:
  - pip
  - python
  - packaging
test:
  imports:
  - sk_sugar
