# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"foo": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://dsm-72.github.io/sugar/"

git_url = "https://github.com/dsm-72/sugar/tree/main/"

def custom_doc_links(name): return None
